### PR TITLE
Feat add flush method on Android

### PR DESCRIPTION
**Pull request by luancurti**
# Summary

Add a method to flush cookies

## Test Plan

Call the `CookieManager.flush` and the cookies should be flushed

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ✅     |

## Checklist

- [X] I have tested this on a device and a simulator
- [X] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by safaiyeh** [comment]
We call flush in varies methods, I'm assuming the motivation behind this PR is that there are cases where it did not call flush correctly.

This begs the question should the methods manage calling flush themselves or the developer should always explicitly call flush?

**Comment by luancurti** [comment]
> We call flush in varies methods, I'm assuming the motivation behind this PR is that there are cases where it did not call flush correctly.
> 
> This begs the question should the methods manage calling flush themselves or the developer should always explicitly call flush?

@safaiyeh I don't know what the motivation I only expose this method because this [issue](https://github.com/react-native-community/cookies/issues/58) @perottilds can you explain with do you need to call this method?

**Comment by perottilds** [comment]
Sure, @luancurti 

Below a method I had to use to workaround the fact that I can't directly flush the cookies when my page first loads.
Since flushing is not immediate, I save the token in async storage (yes it's not safe yada yada) and fetch it as soon as the user opens up the app again, since most interactions with the app have a short life span

```ts
import { LoginData } from '../observables/OnLoginObservable';
import RNCookieManager from '@react-native-community/cookies';
import AsyncStorage from '@react-native-community/async-storage';
import { config } from '../config';

const ACCESS_TOKEN_STORAGE_KEY = 'cookies.accessToken';

export class CookieManager {
  static async handleLogin(_loginData: LoginData | null) {
    const cookies = await RNCookieManager.get(config.DOMAIN);

    if (!cookies || !cookies.accessToken) {
      return;
    }

    await AsyncStorage.setItem(
      ACCESS_TOKEN_STORAGE_KEY,
      JSON.stringify(cookies.accessToken),
    );
  }

  static async setAccessTokenFromStorage() {
    const accessToken = await AsyncStorage.getItem(ACCESS_TOKEN_STORAGE_KEY);

    if (!accessToken) {
      return;
    }

    await RNCookieManager.set(config.DOMAIN, JSON.parse(accessToken));
  }
}
```

**Comment by safaiyeh** [comment]
That makes sense @perottilds thanks!

Appreciate the work on this @luancurti landing this.

**Pull request merged**
