### PR TITLE
Properly check if a cookie belongs to a domain

### PR DESCRIPTION
**Pull request by timrwhi**
# Summary

Resolves https://github.com/react-native-community/cookies/issues/34

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ❌     |

## Checklist

- [x] I have tested this on a device and a simulator
- [x] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [x] I updated the typed files (TS and Flow)
- [x] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by timrwhi** [comment]
@safaiyeh Where can I find `CHANGELOG.md` to update it (per the checklist)?

**Comment by safaiyeh** [comment]
@timrwhi thanks for the PR! `CHANGELOG.md` does not exist :) I'll remove that from the template. I appreciate the PR, ill check it out sometime tomorrow.

**Comment by jhrinoa** [comment]
Any update on this one?

**Comment by safaiyeh** [comment]
Landed appreciate the PR @timrwhi

**Pull request merged**
